#
#  ____            _      ____                   _            _
# | __ )    ___   | |_   / ___|   __ _   _ __   | |_    ___  | |__     __ _
# |  _ \   / _ \  | __| | |      / _` | | '_ \  | __|  / __| | '_ \   / _` |
# | |_) | | (_) | | |_  | |___  | (_| | | |_) | | |_  | (__  | | | | | (_| |
# |____/   \___/   \__|  \____|  \__,_| | .__/   \__|  \___| |_| |_|  \__,_|
#                                       |_|
#                                            published on ğ•ğ•–ğ•ƒğ• ğ•§ğ•–ğ•†ğ•¡ğ•–ğ•Ÿğ•Šğ• ğ•¦ğ•£ğ•”ğ•–â„™ğ•ğ•¦ğ•˜ğ•šğ•Ÿğ•¤

prefix: "&8â”ƒ &bCaptcha &7Ã—"
policyWebsite: "https://mywebsite.com/privacy"

# The timeout is specified in seconds. Use -1 for no time limit
timeout: 30

# Employable types: GUI, CHAT
type: "GUI"

verifyComplete: "%prefix% &7You have been verified!"
verifyTimeoutKick:
  - "%prefix% &7You've been kicked!"
  - "%prefix% &7Reason: &bTimeout!"
  - "%prefix% &7Please try again"

verifyIncorrectKick:
  - "%prefix% &7You've been kicked!"
  - "%prefix% &7Reason: &bIncorrect input!"
  - "%prefix% &7Please try again"

verifyChatMessage: "%prefix% &7Please confirm that you're not a bot and accept the privacy policy(%policyWebsite%) by entering the code below"
verifyChatCodeMessage: "%prefix% &7Your code: &b%code%"

gui:
  inventoryName: "&8Ã— &bVerify"
  itemName: "&8Ã— &bI'm not a bot!"
  itemLore:
    - ""
    - "&8Ã— &7I also confirm the privacy policy (%policyWebsite%)"
    - ""

database:
  # Employable types: MySQL, SQLite, MongoDB
  type: "MySQL"
  mySql:
    host: "localhost"
    database: "YourDatabase"
    username: "YourUsername"
    password: "YourPassword"
    tableName: "CaptchaVerifications"
  sqlite:
    path: "../database/botcaptcha.sqlite"
  mongoDb:
    host: "localhost"
    port: 27017
    username: "YourUsername"
    password: "YourPassword"
    database: "YourDatabase"
    collectionName: "CaptchaVerifications"